apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: otel-demo-dashbord
  namespace: istio-system
spec:
  hosts:
  - otel-demo.IP_TO_REPLACE.nip.io
  gateways:
  - public-gateway
  http:
  - route:
    - destination:
        host: example-frontendproxy.otel-demo.svc.cluster.local
        port:
          number: 6379
    timeout: 30s
